AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
Description: Lambda function and API Gateway setup for D&D Dungeon Master backend.

Parameters:
  LambdaFunctionName:
    Type: String
  LambdaFunctionArn:
    Type: String


Resources:

  # DynamoDB Table
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref AWS::StackName
      AttributeDefinitions:
        - AttributeName: SessionId
          AttributeType: S
      KeySchema:
        - AttributeName: SessionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # API Gateway Rest API
  DungeonMasterApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: DungeonMasterApi

  # API Gateway Resource ({id})
  DungeonMasterResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref DungeonMasterApi
      ParentId: !GetAtt DungeonMasterApi.RootResourceId
      PathPart: "{id}"

  # GET Method
  GetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DungeonMasterApi
      ResourceId: !Ref DungeonMasterResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionArn}:traffic/invocations
          - { LambdaArn: !GetAtt LambdaFunctionArn }

  # POST Method
  PostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DungeonMasterApi
      ResourceId: !Ref DungeonMasterResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionArn}:traffic/invocations
          - { LambdaArn: !GetAtt LambdaFunctionArn }

  # Permission for API Gateway to invoke Lambda
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DungeonMasterApi}/*/*/{id}

  # Deployment of API
  # ApiDeployment:
  #   Type: AWS::ApiGateway::Deployment
  #   Properties:
  #     RestApiId: !Ref DungeonMasterApi
  #   DependsOn:
  #     - GetMethod
  #     - PostMethod

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${DungeonMasterApi}.execute-api.${AWS::Region}.amazonaws.com/prod/{id}"
